name: tag
workdir: ..
ignore:
  - not/relevant/for/tests/*
scripts:
  build: docker build .
  test: echo hello tag
strategies:
  compare-to:
    branch: master
  previous-commit:
    only: master
version: head -1 tag/VERSION
build: echo go building tag!
depends_on:
  - ../../project
env:
  - name: NAMESPACE
    value: "staging"