builds:
  - binary: gally
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/missena-corp/gally/helpers.BuildDate={{.Date}} -X github.com/missena-corp/gally/helpers.Version={{.Tag}}
archive:
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
  format: tar.gz

