builds:
  - binary: gally
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X helpers.BuildDate={{.Date}}
      - -s -w -X helpers.Version={{.Tag}}
archive:
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
