version: 2.1
jobs:
  test:
    working_directory: ~/gally
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Unit Testing
          command: |
            go test -race ./...

workflows:
  version: 2.1
  gally:
    jobs:
      - test:
          filters:
            tags:
              only: /v.*/
            branches:
              only: /.*/

