name: notag
workdir: ..
ignore:
  - not/relevant/for/tests/*
scripts:
  build: docker build .
  test: echo hello notag
strategies:
  compare-to:
    branch: master
  previous-commit:
    only: master
env:
  - name: NAMESPACE
    value: "demo"
