name: notag
context: ..
ignore:
  - not/relevant/for/tests/*
scripts:
  build: docker build .
  test: echo hello notag
strategies:
  compare-to:
    branch: master
  previous-commit:
    only: master
build: echo go building notag!
version: git log -1 --format='%h' ./notag
tag: false
