name: notag
workdir: ..
ignore:
  - not/relevant/for/tests/*
scripts:
  build: docker build .
  test: echo hello notag
strategies:
  compare-to:
    branch: master
  previous-commit:
    only: master
build: echo go building notag!
tag: false
depends_on:
  - ../../repo
env:
  - name: NAMESPACE
    value: "demo"
